# Generated by Django 4.2.16 on 2026-04-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('KGS', 'Кыргызский сом (сом)'), ('KZT', 'Казахстанский тенге (₸)'), ('RUB', 'Российский рубль (₽)'), ('USD', 'Доллар США ($)')], default='KGS', max_length=3, verbose_name='Валюта'),
        ),
    ]
