# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec — AutoParts CRM desktop app.

Output: dist/AutoPartsCRM/
  AutoPartsCRM.exe
  _internal/   ← all Python + app files live here (PyInstaller 6+)

Build with:
    pyinstaller build.spec --clean --noconfirm
(or just run build.bat which calls collectstatic first)
"""

import os

block_cipher = None
base_dir = os.path.dirname(os.path.abspath(SPECPATH))

# ── Data files bundled into _internal/ ───────────────────────────────────────
datas = [
    # Django app packages (Python source)
    ('autoparts',  'autoparts'),
    ('users',      'users'),
    ('catalog',    'catalog'),
    ('warehouse',  'warehouse'),
    ('orders',     'orders'),
    ('crm',        'crm'),
    ('reports',    'reports'),
    ('purchases',  'purchases'),
    ('portal',     'portal'),
    # Templates and pre-collected static files
    ('templates',  'templates'),
    ('staticfiles', 'staticfiles'),   # generated by build.bat → collectstatic
]

# ── Hidden imports (auto-discovered modules that PyInstaller misses) ──────────
hidden = [
    # Django core
    'django',
    'django.contrib.admin',
    'django.contrib.admin.apps',
    'django.contrib.auth',
    'django.contrib.auth.backends',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sessions.backends.db',
    'django.contrib.messages',
    'django.contrib.messages.storage.fallback',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.template.defaulttags',
    'django.template.defaultfilters',
    'django.template.loader_tags',
    'django.templatetags.humanize',
    'django.templatetags.static',
    'django.templatetags.i18n',
    'django.db.backends.sqlite3',
    # Project apps
    'users',   'users.apps',   'users.models',   'users.views',   'users.admin',
    'catalog', 'catalog.apps', 'catalog.models', 'catalog.views', 'catalog.admin',
    'warehouse','warehouse.apps','warehouse.models','warehouse.views','warehouse.admin',
    'orders',  'orders.apps',  'orders.models',  'orders.views',  'orders.admin',
    'crm',     'crm.apps',     'crm.models',     'crm.views',     'crm.admin',
    'reports', 'reports.apps', 'reports.models', 'reports.views',
    'purchases','purchases.apps','purchases.models','purchases.views','purchases.admin',
    'portal',  'portal.apps',  'portal.models',  'portal.views',
    'portal.context_processors', 'portal.urls',
    # Third-party
    'whitenoise',
    'whitenoise.middleware',
    'whitenoise.storage',
    'pandas',
    'openpyxl',
    'openpyxl.styles',
    'openpyxl.utils',
    # pywebview GUI
    'webview',
    'webview.platforms.winforms',
    'clr',
    'System',
    'System.Windows.Forms',
    # wsgiref (stdlib, usually fine but be explicit)
    'wsgiref',
    'wsgiref.simple_server',
    'socketserver',
]

a = Analysis(
    ['run_server.py'],
    pathex=[base_dir],
    binaries=[],
    datas=datas,
    hiddenimports=hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'scipy', 'numpy.distutils'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],                   # no a.binaries/a.datas here — those go into COLLECT
    exclude_binaries=True,
    name='AutoPartsCRM',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    console=False,        # no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,            # set to 'icon.ico' if you have one
)

# COLLECT produces the folder layout:
#   dist/AutoPartsCRM/AutoPartsCRM.exe
#   dist/AutoPartsCRM/_internal/  (all deps)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AutoPartsCRM',
)
