# Generated by Django 4.2.16 on 2026-04-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, help_text='Процент наценки на закупочную цену', max_digits=6, verbose_name='Наценка (%)')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок')),
                ('is_default', models.BooleanField(default=False, help_text='Цена по умолчанию для новых заказов', verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Уровень цены',
                'verbose_name_plural': 'Уровни цен',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_number', models.CharField(db_index=True, max_length=100, verbose_name='OEM номер')),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Артикул')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='Бренд')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Цена из прайс-листа / цена закупки', max_digits=12, verbose_name='Закупочная цена')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Остаток')),
                ('min_stock', models.IntegerField(default=0, verbose_name='Мин. остаток')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Место хранения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
