# Generated by Django 4.2.16 on 2026-04-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='analogs',
            field=models.ManyToManyField(blank=True, to='catalog.product', verbose_name='Аналоги/Кроссы'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Штрихкод'),
        ),
    ]
