# Generated by Django 4.2.16 on 2026-04-04 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_product_analogs_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_makes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.carmake', verbose_name='Марка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
                'ordering': ['make__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='compatible_models',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.carmodel', verbose_name='Совместимые авто'),
        ),
    ]
