# Generated by Django 4.2.16 on 2026-04-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_shift_expensecategory_expense'),
        ('orders', '0004_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.shift', verbose_name='Смена'),
        ),
    ]
