# Generated by Django 4.2.16 on 2026-04-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='synclog',
            new_name='desktop_syn_synced_21b329_idx',
            old_name='desktop_syn_synced_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='synclog',
            new_name='desktop_syn_app_lab_ab7761_idx',
            old_name='desktop_syn_app_mod_obj_idx',
        ),
    ]
